### ISSUE TITLE
add codcovee yaml

### ISSUE THREAD

**Issue by gevahn** [MolSSI-SSS/QM_2017_SSS_Team3#17]
add a codecov yaml to not track setup and tests

**Comment by cefitzge** [comment]
```
comment:
  layout: header, changes, diff
coverage:
  ignore:
    - test/.*
    - setup.py
  status:
patch: false
```
